Redis:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  command:
  - redis-server
  - /usr/local/etc/redis/redis.conf
  image: redis
  volumes:
  - /home/data/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
  stdin_open: true
phpRedisAdmin:
  ports:
  - ${ADMIN_PORT}:80/tcp
  environment:
    REDIS_1_HOST: redis
    REDIS_1_PORT: '6379'
    ADMIN_USER: admin
    ADMIN_PASS: ${ADMIN_PASS}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: pataquets/phpredisadmin
  links:
  - Redis:redis
  stdin_open: true
