Minecraft-Static:
  environment:
    EULA: 'true'
    MOTD: ${SERVER_ID}:${SERVER_IP}:${SERVER_PORT}
    SERVER_PORT: ${SERVER_PORT}
    TYPE: SPIGOT
    CONSOLE: 'false'
    RAM_OPTS: ${RAM_OPTS}
    TZ: Asia/Bangkok
    SERVER: 'spigot_server.jar'
  tty: false
  image: pcxd/minecraft-server-static
  volumes:
  - /home/data/minecraft/${FOLDER_NAME}:/tmp/data
  stdin_open: false
  external_links:
  - Redis/Redis:redis
  - MySQL/MariaDB:db
  ports:
  - ${SERVER_PORT}:${SERVER_PORT}/udp
  - ${SERVER_PORT}:${SERVER_PORT}/tcp
  net: host
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.dns: 'true'

